server:
  tomcat:
    max-threads: 2 #??? ??? . ?? ?? ?
    min-spare-threads: 2 #?? ??? ?? ?? ??? ?
  port: 2080

spring:
  application:
    name: securityExam

#  security:
#    user:
#      name: tjdals
#      password: 123
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23lisJMtsbsfa9MjDT
            client-secret: LyfTfHCxWZ5eMVFY+bQ3reBtT9vJLSLpD0uRlFtKgyI=
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012